version: "3.7"
services:
    # Custom App
    custom-auth-interface: #Custom-Auth-Interface
        image: custom-auth-interface:1.0
        ports:
            - "8080:8080"
        environment:
            - PORT=8080
            - BASE_URL=http://127.0.0.1:8080
            - CLIENT_ID=226295e4-4198-42d3-849e-819459eb4179
            - CLIENT_SECRET=zH~l3ePcCZH.Z_yzgXvgPrg_ND
            - HYDRA_PUBLIC_URL=http://127.0.0.1:4444
            - HYDRA_ADMIN_URL=http://127.0.0.1:4445
            - KRATOS_PUBLIC_URL=http://127.0.0.1:4433
        networks:
            - intranet
        restart: on-failure

    # Hydra Setup
    hydra:
        image: oryd/hydra:v2.2.0
        ports:
            - "4444:4444" # Public port
            - "4445:4445" # Admin port
            - "5555:5555" # Port for hydra token user
        volumes:
            - type: bind
              source: ./ory-hydra-kratos-config
              target: /etc/config/hydra
        environment:
            - DSN=postgres://pteam:appointyadmin@34.134.190.227:5432/pteam_hydra
        command: serve -c /etc/config/hydra/hydra.yml all --dev
        restart: unless-stopped
        depends_on:
            - hydra-migrate
        networks:
            - intranet

    hydra-migrate:
        image: oryd/hydra:v2.2.0
        environment:
            - DSN=postgres://pteam:appointyadmin@34.134.190.227:5432/pteam_hydra
        command: migrate -c /etc/config/hydra/hydra.yml sql -e --yes
        volumes:
            - type: bind
              source: ./ory-hydra-kratos-config
              target: /etc/config/hydra
        restart: on-failure
        networks:
            - intranet

    # Kratos Setup
    kratos-migrate:
        image: oryd/kratos:v1.2.0
        environment:
            - DSN=postgres://pteam:appointyadmin@34.134.190.227:5432/pteam_kratos
        volumes:
            - type: bind
              source: ./ory-hydra-kratos-config
              target: /etc/config/kratos
        command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
        restart: on-failure
        networks:
            - intranet

    kratos-custom-ui: #Kratos UI: sign up, sign in, logout, etc
        image: custom-kratos-ui:1.0
        ports:
            - "4455:4455"
        environment:
            - KRATOS_PUBLIC_URL=http://kratos:4433/
            - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
            - HYDRA_ADMIN_URL=http://hydra:4445
            - PORT=4455
            - COOKIE_SECRET=SuperSecretCookie # not included in quick-start.yml
            - CSRF_COOKIE_NAME=__OryKratosApp # not included in quick-start.yml
            - CSRF_COOKIE_SECRET=SuperSecretCookieCsrf # not included in quick-start.yml
        networks:
            - intranet
        restart: on-failure

    kratos:
        depends_on:
            - kratos-migrate
        image: oryd/kratos:v1.2.0
        ports:
            - "4433:4433" # public
            - "4434:4434" # admin
        restart: unless-stopped
        environment:
            - DSN=postgres://pteam:appointyadmin@34.134.190.227:5432/pteam_kratos
        command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
        volumes:
            - type: bind
              source: ./ory-hydra-kratos-config
              target: /etc/config/kratos
        networks:
            - intranet

    mailslurper:
        image: oryd/mailslurper:latest-smtps
        ports:
            - "4436:4436"
            - "4437:4437"
        networks:
            - intranet

networks:
    intranet:
volumes:
    hydra-sqlite:
    kratos-sqlite:
