version: v1.1.0

dsn: postgres://pteam:an3%29Ui-%3EfJGVXP%7CD@34.134.190.227:5432/pteam_kratos

serve:
    public:
        base_url: http://127.0.0.1:4433
        cors:
            enabled: true
    admin:
        base_url: http://127.0.0.1:4434

selfservice:
    default_browser_return_url: http://127.0.0.1:4455
    allowed_return_urls:
        - http://127.0.0.1:4455

    methods:
        password:
            enabled: true
            config:
                min_password_length: 6
                identifier_similarity_check_enabled: false
                haveibeenpwned_enabled: false
        code:
            passwordless_enabled: true
            enabled: true
            config:
                lifespan: 15m
        oidc:
            config:
                providers:
                    - id: google-kratos-poc # this is `<provider-id>` in the Authorization callback URL. DO NOT CHANGE IT ONCE SET!
                      label: Google
                      provider: google
                      client_id: 756128683118-hirbke6jtbdkvcs4qa5q86si12840gne.apps.googleusercontent.com # Replace this with the OAuth2 Client ID
                      client_secret: ADD_YOUR_CLIENT_SECRET # Replace this with the OAuth2 Client secret
                      mapper_url: "base64://bG9jYWwgY2xhaW1zID0gewogIGVtYWlsX3ZlcmlmaWVkOiBmYWxzZSwKfSArIHN0ZC5leHRWYXIoJ2NsYWltcycpOwoKewogIGlkZW50aXR5OiB7CiAgICB0cmFpdHM6IHsKICAgICAgW2lmICdlbWFpbCcgaW4gY2xhaW1zICYmIGNsYWltcy5lbWFpbF92ZXJpZmllZCB0aGVuICdlbWFpbCcgZWxzZSBudWxsXTogY2xhaW1zLmVtYWlsLAogICAgICBmaXJzdF9uYW1lOiBjbGFpbXMuZ2l2ZW5fbmFtZSwKICAgICAgbGFzdF9uYW1lOiBjbGFpbXMuZmFtaWx5X25hbWUsCiAgICAgIFtpZiAnaGQnIGluIGNsYWltcyAmJiBjbGFpbXMuZW1haWxfdmVyaWZpZWQgdGhlbiAnaGQnIGVsc2UgbnVsbF06IGNsYWltcy5oZCwKICAgIH0sCiAgfSwKfQ=="
                      scope:
                          - email
                          - profile
                      # other supported scopes can be found in Google OAuth 2.0 dev docs
                      requested_claims:
                          id_token:
                              email:
                                  essential: true
                              email_verified:
                                  essential: false
                              given_name:
                                  essential: true
                              family_name: null
                              hd: null
            enabled: true

    flows:
        error:
            ui_url: http://127.0.0.1:4455/error
        settings:
            ui_url: http://127.0.0.1:4455/settings
            privileged_session_max_age: 15m
            required_aal: highest_available
        logout:
            after:
                default_browser_return_url: http://127.0.0.1:8080
        login:
            ui_url: http://127.0.0.1:4455/login
            after:
                password:
                    hooks:
                        - hook: require_verified_address
        verification:
            use: code
            enabled: true
            ui_url: http://127.0.0.1:4455/verification
            lifespan: 15m
            notify_unknown_recipients: true
            after:
                default_browser_return_url: http://127.0.0.1:8080
        registration:
            ui_url: http://127.0.0.1:4455/registration
            after:
                password:
                    hooks:
                        - hook: session
                default_browser_return_url: http://127.0.0.1:4455/verification
            enabled: true
        recovery:
            enabled: true
            ui_url: http://127.0.0.1:4455/recovery
            lifespan: "1h"
            use: code
            notify_unknown_recipients: true

log:
    format: text
    leak_sensitive_values: true
    level: debug

secrets:
    cookie:
        - CHANGE_ME_TO_REAL_SECRET
    cipher:
        - 32-LONG-SECRET-NOT-SECURE-AT-ALL

identity:
    default_schema_id: default
    schemas:
        - id: default
          url: file:///etc/config/kratos/identity.schema.json # Important: identity schema

courier:
    smtp:
        connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
        from_name: JACK_MAIL_SERVICE
        from_address: no-replay-jack@test.com

oauth2_provider:
    url: http://hydra:4445 # Important: hydra admin URL
